name: spring-data-jpa
description: Template criado para configurar o banco de dados
display-name: spring-data-jpa
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/plugin/#category
compatibility:
  - java
  - spring
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies
  - "Api"
  - "Java"
  - "Springboot"
types:
  - app
inputs:
  - label: Defina o login para acesso do banco
    type: text
    name: login
  - label: Defina a senha para acesso do banco
    type: text
    name: senha
  - label: Defina a string de conexão para acesso do banco
    type: text
    name: string_conexao
  - label: Escolha o tipo de banco de dados para sua aplicação
    type: text
    name: driver
    items:
      - MySQL
      - PostgreSQL
  - label: Desabilita transacao por default para repositorios
    type: bool
    name: desabilita_transacao
    default: false
  - label: Nome completo da classe que inicia a aplicação. Ex - br.com.org.projeto.Application
    type: text
    name: classe_application        

hooks: 
  - type: edit
    trigger: after-render
    path: pom.xml
    conditions:
      variable: driver
      operator: ==
      value: MySQL
    changes:
      - search: 
          string: </dependencies>
          insert-before:
            snippet: snippets/mysql.xml
          when:
            not-exists-snippet: snippets/mysql.xml

  - type: edit
    trigger: after-render
    path: pom.xml
    conditions:
      variable: driver
      operator: ==
      value: PostgreSQL
    changes:
      - search: 
          string: </dependencies>
          insert-before:
            snippet: snippets/postgre.xml
          when:
            not-exists-snippet: snippets/postgre.xml

  - type: edit
    trigger: after-render
    path: "src/main/java/{{inputs.classe_applicaion | replace('.','/')}}.java"
    conditions:
      variable: desabilita_transacao
      operator: ==
      value: true
    changes:
      - search: 
          string: "@SpringBootApplication"
          insert-before:
            value: "EnableJpaRepositories(enableDefaultTransactions = false)\n"